Refactor healthcheck endpoints
SwiftInvention/scala-zio.g8 pull request #16
Opened 2022-11-24 22:33 UTC by VladimirLogachev

2022-11-24 23:07 UTC, VladimirLogachev commented on src/main/g8/$name;format="normalize"$/src/main/scala/$package$/db/repository/HealthCheckHelper.scala
> +    .as(())
Because the only thing we are interested in is if the operation is successful. The unit value represents exactly that.

2022-11-24 23:10 UTC, VladimirLogachev commented on src/main/g8/$name;format="normalize"$/src/main/scala/$package$/Application.scala
> +    ZioHttpInterpreter().toHttp(SwaggerApiEndpoint.common) @@ composedMiddlewares
I just switched it from `common` to `SwaggerApiEndpoint.common` to make it more obvious.
I don't think of a composed endpoint as some sort of Util or Helper.
I don't mind changing this name in the future, but not exactly to `SwaggerUtil`.

2022-11-24 23:46 UTC, VladimirLogachev commented on src/main/g8/$name;format="normalize"$/src/main/scala/$package$/Application.scala
> +    ZioHttpInterpreter().toHttp(SwaggerApiEndpoint.common) @@ composedMiddlewares
I would prefer to keep only the `Endpoint` part.
Anyway, it's unrelated to my changes.

2022-11-25 07:19 UTC, kolebakin requested changes

2022-11-25 07:30 UTC, VladimirLogachev commented on src/main/g8/project/Dependencies.scala
> +    "io.d11"                       % "zhttp_2.13"              % Versions.zioHttpVersion,
Yes, for clarity

2022-11-25 07:31 UTC, VladimirLogachev commented on src/main/g8/project/plugins.sbt
> +// addDependencyTreePlugin
It is now integrated into sbt itself

2022-11-25 07:43 UTC, kolebakin approved these changes

2022-11-25 07:44 UTC, merged