Add PersonEndpoint and Run-method at Application
SwiftInvention/scala-zio.g8 pull request #9
Opened 2022-11-17 15:15 UTC by komXXme

Change Dependencies

2022-11-17 17:06 UTC, VladimirLogachev requested changes
Nice job! But there are some things to clean up.

2022-11-17 17:13 UTC, VladimirLogachev commented
Also, please add 
`- OpenJDK 11`
to the `## Prerequisites` section of the readme.

2022-11-20 13:59 UTC, kolebakin approved these changes

2022-11-21 10:03 UTC, VladimirLogachev commented on src/main/g8/$name;format="normalize"$/src/main/scala/$package$/Application.scala
> +      _ <- Console.readLine
Why do you think we need the server to go down with a single keystroke? Maybe remove it?

2022-11-21 12:27 UTC, merged